---
title: "Mapa de infraestructura verde del cantón de San José"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
#-------------------- Paquetes --------------------

library(flexdashboard)
library(dplyr)
library(sf)
library(leaflet)
library(leafem)
library(esri2sf)
library(raster)

#--------- URL de geoservicios y datos ------------

url_agfs_limite_sanjose <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_limite_san_jose/FeatureServer/0"

url_raster_infraestructura_verde <-
  "https://raw.githubusercontent.com/atlas-servicios-ecosistemicos-gam/datos/master/infraestructura-verde/sanjose/IV_SAN_JOSE_WEB.TIF"

#--------------- Objetos sf y raster --------------

# Límite de San José
sf_limite_sanjose <- 
  esri2sf(url_agfs_limite_sanjose)

# Límite de San José (reproyectado a Web Mercator)
sf_limite_sanjose_web <- 
  sf_limite_sanjose %>%
  st_transform(3857)

# Capa raster de infraestructura verde (en Web Mercator)
raster_infraestructura_verde <-
  raster(url_raster_infraestructura_verde) %>%
  aggregate(fact=c(2), fun=modal) %>% # ¡¡HAY QUE TRATAR DE ELIMINAR ESTA AGRUPACIÓN. PODRÍA FUNCIONAR AL USAR MÁS MEMORIA LINUX!!
  crop(sf_limite_sanjose_web) %>%
  mask(sf_limite_sanjose_web)

#---------------- Paletas de colores ---------------

colores_infraestructura_verde <- 
  c(rgb(106,142,88, maxColorValue=255), rgb(64,131,136, maxColorValue=255), 
    rgb(73,230,0,   maxColorValue=255), rgb(105,255,71, maxColorValue=255), 
    rgb(0,83,102,   maxColorValue=255), rgb(255,255,0,  maxColorValue=255), 
    rgb(145,172,128,maxColorValue=255), rgb(217,217,214,maxColorValue=255), 
    rgb(91,63,54,   maxColorValue=255), rgb(109,145,64, maxColorValue=255), 
    rgb(71,106,48,  maxColorValue=255), rgb(255,252,188,maxColorValue=255), 
    rgb(171,205,102,maxColorValue=255), rgb(137,90,68,  maxColorValue=255), 
    rgb(220,212,148,maxColorValue=255)
  )

etiquetas_infraestructura_verde <- 
  c("Bosques y arbolados periurbanos", "Bosques y arbolados en la ribera de los ríos", 
    "Parques y jardines pequeños con árboles", "Campos deportivos y recreativos", 
    "Lagunas estacionales de agua dulce", "Arbolados dispersos", 
    "Terrenos baldíos (matorrales)", "Superficie no pavimentada", 
    "Superficie pavimentada", "Arbolados a lo largo de la vía férrea", 
    "Arbolados a lo largo de autopistas", "Pastos cultivados", 
    "Cultivos perennes", "Cafetales arbolados",
    "Terrenos baldíos (pastos)"
    )

values_infraestructura_verde <- c(1, 3, 4, 7, 8, 9, 10, 11, 12, 14, 15, 19, 20, 21, 22)

pal <- colorFactor(
  palette = colores_infraestructura_verde, 
  domain = values_infraestructura_verde,
  na.color = "transparent"
)

```

Row
-----------------------------------------------------------------------

### Datos para descarga: [Capa de infraestructura verde del cantón de San José](https://raw.githubusercontent.com/atlas-servicios-ecosistemicos-gam/datos/master/infraestructura-verde/sanjose/IV_SAN_JOSE.TIF)
```{r}

leaflet() %>%
  setView(-84.09, 9.94, 13) %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
  addProviderTiles(providers$CartoDB.DarkMatter, group = "CartoDB Dark Matter") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
  addPolygons(
    data = sf_limite_sanjose,
    color = "Purple",
    fillColor = "transparent",
    stroke = TRUE,
    weight = 6.0,
    group = "Límite de San José"
  ) %>%
  addRasterImage(
    raster_infraestructura_verde,
    colors = pal,
    opacity = 1,
    group = "Infraestructura verde"
  ) %>%
  addLegend(
    title = "Infraestructura verde", 
    position = "bottomright",
    colors = colores_infraestructura_verde, 
    labels = etiquetas_infraestructura_verde,
    group = "Infraestructura verde"
  ) %>%
  addLayersControl(
    baseGroups = c("OpenStreetMap", "Stamen Toner Lite", "CartoDB Dark Matter", "Imágenes de ESRI"),
    overlayGroups = c("Límite de San José", "Infraestructura verde"),
    options = layersControlOptions(collapsed = TRUE)    
  ) %>%  
  addMiniMap(
    toggleDisplay = TRUE,
    position = "bottomleft",
    tiles = providers$OpenStreetMap.Mapnik
  ) %>%
  addScaleBar(
    position = "bottomleft",
    options = scaleBarOptions(imperial = FALSE)
  ) %>%
  addMouseCoordinates()

```